vscode:
  extensions:
    - danielpinto8zz6.c-cpp-compile-run@1.0.5:XSyaIAQHwI9Ee9oWKzPv5A==
    - ms-vscode.cpptools@0.26.3:u3GsZ5PK12Ddr79vh4TWgQ==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - formulahendry.code-runner@0.9.16:mygIe4p5pO3AgKH5EtQiWA==